import { useEffect, useRef, useState } from 'react'
import { BankingProvider, useBank } from './BankContext'
import Icon from './Icon'
import VoiceCall, { useVoice } from './VoiceCall'
import './banking.css'
const money = value => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value ?? 0)
const dateLabel = value => value ? new Intl.DateTimeFormat('es-SV', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value + 'T12:00:00')) : '—'
const timeLabel = value => new Intl.DateTimeFormat('es-SV', { hour: '2-digit', minute: '2-digit' }).format(new Date(value))
const statuses = { UPCOMING: 'Próximo a vencer', RESCHEDULED: 'Nueva fecha registrada', PAID: 'Cuota pagada', PARTIAL: 'Pago parcial registrado', SAVING: 'Ahorro programado' }
const productIcon = code => code === 'VEHICLE_LOAN' ? 'car' : code?.includes('HOME') || code?.includes('MORTGAGE') ? 'home' : 'wallet'
function Button({ children, onClick, secondary = false, icon, className = '', disabled, ...props }) {
 const { busy } = useBank()
 return <button className={`button ${secondary ? 'secondary' : 'primary'} ${className}`} onClick={onClick} disabled={busy || disabled} {...props}>{icon && <Icon name={icon}/>} {children}</button>
}
function RoundIcon({ name, tone = 'yellow', alert = false, size = 32 }) { return <span className={`round-icon ${tone}`}><Icon name={name} size={size}/>{alert && <b className="alert-dot">!</b>}</span> }
function Money({ value, hidden = false }) { const [units, cents] = money(value).split('.'); return <span className="money">{hidden ? '••••' : <>{units}<sup>{cents}</sup></>}</span> }
function Title({ title = 'BA A Tiempo', subtitle, badge, back = 'inicio' }) {
 const { navigate } = useBank()
 return <div className="page-heading"><button className="icon-button back" aria-label="Volver" onClick={() => navigate(back)}><Icon name="back" size={28}/></button><div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div>{badge && <span className="badge">{badge}</span>}</div>
}
function Header() {
 const { navigate, state } = useBank()
 return <header className="app-header"><button className="brand" aria-label="Bancoagrícola, inicio" onClick={() => navigate('inicio')}><span/><span/><span/></button><div className="header-actions"><button onClick={() => navigate('mensajeria')}><span className="notification-icon"><Icon name="bell" size={27}/>{state.intervention.show && <i/>}</span><span>Mensajería</span></button><button onClick={() => navigate('perfil')}><Icon name="user" size={27}/><span>Perfil</span></button><button onClick={() => navigate('qr')}><span className="qr-icon"><Icon name="qr" size={23}/></span><span>Mi QR</span></button></div></header>
}
function BottomNav() {
 const { page, navigate } = useBank(); const active = ['productos','gestiones','parati'].includes(page) ? page : 'inicio'
 return <nav className="bottom-nav" aria-label="Navegación principal">{[['inicio','home','Inicio'],['productos','card','Mis Productos'],['gestiones','hand','Gestiones'],['parati','gift','Para Ti']].map(([route,icon,label]) => <button key={route} aria-current={active === route ? 'page' : undefined} className={active === route ? 'active' : ''} onClick={() => navigate(route)}><Icon name={icon} size={27}/><span>{label}</span></button>)}</nav>
}
function PreventiveCard({ product = false }) {
 const { state,navigate,command } = useBank()
 const help = () => navigate(state.intervention.human ? 'support' : state.intervention.guided ? 'guided' : 'ayuda')
 if (!state.intervention.show) return null
 return <section className="preventive-card"><div className="preventive-heading"><RoundIcon name="calendar" alert size={38}/><div><div className="title-line"><h2>BA A Tiempo</h2>{!product && <span className="badge tagline">Previene, te da tranquilidad</span>}</div><h3>{product ? 'Tu próximo pago' : 'Tu próximo pago vence pronto'}</h3><p>{product ? 'Pagar a tiempo te ayuda a mantener un buen historial crediticio y seguir cumpliendo tus metas.' : 'Revisarlo con anticipación puede ayudarte a mantenerlo al día.'}</p></div></div>{product && <div className="payment-details"><div><span>Monto a pagar</span><Money value={state.product.remaining}/></div><div><span>Fecha de vencimiento</span><strong>{dateLabel(state.product.due_date)}</strong></div></div>}<div className="stack-actions">{product ? <><Button onClick={help}>Necesito ayuda con este pago</Button><Button secondary onClick={() => command('select',{offer_id:'PAY_NOW'})}>Pagar ahora</Button></> : <><Button onClick={() => command('select',{offer_id:'PAY_NOW'})}>Pagar ahora</Button><Button secondary onClick={() => navigate('ayuda')}>Revisar opciones</Button><Button secondary onClick={help}>Necesito ayuda</Button></>}</div></section>
}
function Home() {
 const {state,navigate} = useBank(); const [hidden,setHidden] = useState(false)
 return <><section className="greeting"><span className="profile-ring"><Icon name="user"/></span><div><button onClick={() => navigate('perfil')}>Hola {state.name} <Icon name="arrow" size={19}/></button><p>Última visita: {new Intl.DateTimeFormat('es-SV').format(new Date(state.created_at))} | {timeLabel(state.created_at)}</p></div></section><div className="home-content"><div className="section-label"><h2>Mis cuentas <button className="icon-button" aria-label={hidden ? 'Mostrar saldos' : 'Ocultar saldos'} onClick={() => setHidden(!hidden)}><Icon name="eye"/></button></h2><button className="text-link" onClick={() => navigate('cuentas')}>Ver todas <Icon name="arrow" size={18}/></button></div><div className="accounts">{state.accounts.map(a => <button className="account-card" key={a.id} onClick={() => navigate('cuentas')}><Icon name="pig" size={34}/><div><h3>{a.name}</h3><span>CUENTA DIGITAL</span><Money value={a.balance} hidden={hidden}/><p>Saldo disponible</p></div></button>)}</div><PreventiveCard/>{state.receipt && <button className="success-banner" onClick={() => navigate('receipt')}><RoundIcon name="check" tone="mint"/><div><strong>{statuses[state.product.status]}</strong><span>Ver tu comprobante</span></div><Icon name="arrow"/></button>}{!state.intervention.show && !state.receipt && <div className="quiet-card"><RoundIcon name="check" tone="mint"/><div><h3>Tu tranquilidad, primero</h3><p>{state.snoozed ? 'Guardamos tu preferencia. Puedes revisar tu pago cuando lo necesites.' : 'Tus productos están disponibles para que los consultes cuando quieras.'}</p></div></div>}<h2 className="section-question">¿Qué necesitas hacer hoy?</h2><div className="quick-actions">{[['transfer','pink','Transferir dinero','transferir'],['phone','mint','Recargar celular','servicios'],['card','yellow','Pagar tarjeta','productos'],['file','gray','Pagar servicios','servicios']].map(([icon,tone,label,route]) => <button key={label} onClick={() => navigate(route)}><RoundIcon name={icon} tone={tone}/><span>{label}</span></button>)}</div><button className="promotion" onClick={() => navigate('parati')}><Icon name="gift" size={30}/><strong>Promociones y descuentos</strong><Icon name="arrow"/></button></div></>
}
function ProductCard() {
 const {state} = useBank(); const p = state.product
 return <section className="product-card"><div className="product-heading"><Icon name={productIcon(p.code)} size={43}/><div><h2>{p.name}</h2><span>CRÉDITO</span><p>N° {p.number}</p></div><span className={'badge '+(p.status === 'PAID' ? 'mint' : '')}>{p.status === 'UPCOMING' && <b>!</b>}{statuses[p.status]}</span></div><div className="product-details"><div><span>Saldo pendiente</span><Money value={p.outstanding}/></div><div><span>Cuota mensual</span><Money value={p.installment}/></div><div><span>Próxima fecha de pago</span><strong>{p.status === 'PAID' ? 'Al día' : dateLabel(p.due_date)}</strong></div></div></section>
}
function CreditSwitcher(){
 const {state,command}=useBank(); if(!state.products||state.products.length<2)return null
 return <div className="option-list">{state.products.map(p=>{const active=p.id===state.product.id;return <button className="option-row" key={p.id} aria-pressed={active} onClick={()=>!active&&command('select_product',{product_id:p.id})}><RoundIcon name={productIcon(p.code)} tone={p.status==='PAID'?'mint':'yellow'} alert={p.status!=='PAID'}/><span><strong>{p.name}</strong><small>{statuses[p.status]}</small></span><Icon name={active?'check':'arrow'}/></button>})}</div>
}
function Products({initialTab='creditos'}) {
 const {state,command,navigate}=useBank(); const [tab,setTab]=useState(initialTab)
 return <><div className="simple-heading"><h1>Mis productos</h1><p>Aquí puedes ver y gestionar todos tus productos.</p></div><div className="tabs" role="tablist" aria-label="Productos">{[['cuentas','Cuentas'],['tarjetas','Tarjetas'],['creditos','Créditos']].map(([id,label]) => <button role="tab" aria-selected={tab===id} className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div><div className="page-content">{tab==='creditos'?<><CreditSwitcher/><ProductCard/><PreventiveCard product/>{!state.intervention.show&&<div className="stack-actions standalone">{state.product.remaining>0&&<Button onClick={()=>command('select',{offer_id:'PAY_NOW'})}>Pagar ahora</Button>}<Button secondary onClick={()=>navigate(state.receipt?'receipt':'ayuda')}>{state.receipt?'Ver comprobante':'Consultar mi próximo pago'}</Button></div>}<button className="history-link" onClick={()=>navigate('historial')}><Icon name="file" size={30}/>Ver historial<Icon name="arrow" size={18}/></button></>:tab==='cuentas'?<><h2>Tus cuentas de ahorro</h2>{state.accounts.map(a=><div className="account-detail card" key={a.id}><RoundIcon name="pig" tone="blue"/><div><h3>{a.name}</h3><p>Cuenta digital {a.number}</p><Money value={a.balance}/><p>Saldo disponible</p></div></div>)}<p className="muted">Los saldos son ficticios y solo se utilizan en esta demostración.</p></>:<div className="empty-state"><RoundIcon name="card"/><h2>No tienes tarjetas en este perfil</h2><p>Puedes consultar tu crédito y su próximo pago en la pestaña Créditos.</p><Button onClick={()=>setTab('creditos')}>Ver mi crédito</Button></div>}</div></>
}
function CompactProduct(){const {state}=useBank();return <div className="compact-product card"><RoundIcon name={productIcon(state.product.code)}/><div><h3>{state.product.name}</h3><p>Tu crédito</p></div><div className="compact-payment"><span>Próximo pago</span><Money value={state.product.remaining}/><p>Vence el {dateLabel(state.product.due_date)}</p></div></div>}
const helpOptions=[['card','mint','Puedo pagarlo ahora','Quiero hacer el pago en este momento.','PAY'],['calendar','yellow','Me pagan después','Recibiré el dinero pronto.','Me pagan después'],['pie','pink','No puedo cubrirlo completo','Quiero explorar opciones de pago parcial.','No puedo cubrirlo completo'],['phone','blue','Necesito ayuda con la app','Tengo un problema para realizar el pago.','GUIDED'],['user','purple','Quiero hablar con una persona','Prefiero que un asesor me contacte.','HUMAN']]
function Help(){const {command,navigate}=useBank();const [text,setText]=useState('');const choose=async value=>{if(value==='PAY')return command('select',{offer_id:'PAY_NOW'});if(value==='GUIDED')return navigate('guided');if(value==='HUMAN')return navigate('support');navigate('chat');await command('message',{text:value})};return <><Title back="productos"/><div className="page-content"><CompactProduct/><div className="question-heading"><h2>¿Qué sucede con este pago?</h2><p>Cuéntanos para mostrarte la mejor opción.</p></div><div className="option-list">{helpOptions.map(([icon,tone,title,subtitle,value])=><button className="option-row" key={title} onClick={()=>choose(value)}><RoundIcon name={icon} tone={tone}/><span><strong>{title}</strong><small>{subtitle}</small></span><Icon name="arrow"/></button>)}</div><form className="help-form" onSubmit={e=>{e.preventDefault();if(text.trim())choose(text)}}><label htmlFor="help-message">También puedes escribir lo que sucede</label><div className="textarea-wrap"><textarea id="help-message" value={text} onChange={e=>setText(e.target.value)} placeholder="Cuéntanos en tus palabras…" maxLength={300}/><span>{text.length}/300</span></div>{text.trim()&&<Button type="submit">Continuar <Icon name="arrow" size={18}/></Button>}</form></div></>}
function OfferDetails({offer}){const {state}=useBank();if(offer.date)return <><strong className="offer-value">Compromiso de pago: {dateLabel(offer.date)}</strong><p>Registra esta fecha autorizada para tu crédito. Esta operación es una simulación.</p></>;if(offer.min_amount)return <><strong className="offer-value">Pago parcial: {money(offer.min_amount)}</strong><p>Equivale al {offer.min_percentage}% de tu cuota. El saldo restante seguirá pendiente; no implica una condonación.</p></>;if(offer.percentage)return <><strong className="offer-value">Apartar el {Number((offer.percentage*100).toFixed(2))}% de tus ingresos</strong><p>Programa un apartado para tu próximo pago. Esta opción no otorga un nuevo crédito.</p></>;if(offer.human_only)return <p>Un asesor revisará tu caso. No se modifica tu crédito automáticamente.</p>;return <p>{offer.type==='PAY_NOW'?`Cuota pendiente: ${money(state.product.remaining)}.`:'Te ayudamos a revisar esta alternativa para tu producto.'}</p>}
function Offers(){const {state,command}=useBank();return <div className="offers">{state.offers.map(offer=><section className="offer-card" key={offer.alt_id}><div className="offer-heading"><RoundIcon name={offer.icon}/><div><h3>{offer.title}</h3><OfferDetails offer={offer}/></div></div><Button onClick={()=>command('select',{offer_id:offer.alt_id})}>{offer.date?'Usar esta fecha':offer.human_only?'Solicitar revisión':'Revisar esta opción'}</Button></section>)}</div>}
function Chat({whatsapp=false}){
 const {state,command,busy,navigate,setCallOpen}=useBank();const [text,setText]=useState('');const endRef=useRef(null);const voice=useVoice(value=>command('message',{text:value}))
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[state.messages.length,busy])
 const send=async e=>{e.preventDefault();if(!text.trim())return;const message=text;setText('');await command('message',{text:message})}
 return <div className={'chat-page '+(whatsapp?'whatsapp-page':'')}><div className="chat-header"><button className="icon-button" aria-label="Volver" onClick={()=>navigate(whatsapp?'mensajeria':'ayuda')}><Icon name="back"/></button><RoundIcon name={whatsapp?'whatsapp':'calendar'} tone={whatsapp?'mint':'yellow'}/><div><h1>{whatsapp?'Bancoagrícola':'BA A Tiempo'}</h1><p>{whatsapp?'WhatsApp · conversación simulada':'Asistencia preventiva'}</p></div><button className="icon-button" aria-label="Llamar al asistente" onClick={()=>setCallOpen(true)}><Icon name="call"/></button></div><div className="chat-messages"><div className="message-row assistant"><RoundIcon name="robot"/><div><p className="bubble">Hola, veo que tu próximo pago {state.product.status==='PAID'?'está al día':'vence pronto'}.<br/>¿Qué sucede con este pago?</p><span className="message-time">{timeLabel(state.created_at)}</span></div></div>{state.messages.map(m=><div className={`message-row ${m.role}`} key={m.id}>{m.role==='assistant'&&<RoundIcon name="robot"/>}<div><p className="bubble">{m.content}</p><span className="message-time">{timeLabel(m.at)} {m.role==='user'&&'✓✓'}</span></div></div>)}{busy&&<div className="typing" aria-label="Preparando respuesta"><i/><i/><i/></div>}{state.barrier&&!state.pending_offer&&!state.receipt&&<Offers/>}{state.support&&<button className="success-banner" onClick={()=>navigate('support')}><Icon name="check"/><strong>Solicitud registrada · {state.support.id}</strong><Icon name="arrow"/></button>}{state.receipt&&<button className="success-banner" onClick={()=>navigate('receipt')}><Icon name="check"/><strong>Tu producto se actualizó</strong><Icon name="arrow"/></button>}<div ref={endRef}/></div>{!state.barrier&&state.messages.length<2&&<div className="chat-suggestions">{['Me pagan después','No puedo cubrirlo completo'].map(t=><button key={t} onClick={()=>command('message',{text:t})}>{t}</button>)}</div>}<div className="chat-tools"><button onClick={()=>command('select',{offer_id:'PAY_NOW'})}><Icon name="card" size={18}/>Pagar ahora</button><button onClick={()=>navigate('support')}><Icon name="headset" size={18}/>Hablar con asesor</button></div>{voice.voiceError&&<p className="voice-note">{voice.voiceError}</p>}<form className="chat-composer" onSubmit={send}><div><input aria-label="Escribe un mensaje" placeholder={voice.listening?'Escuchando…':'Escribe un mensaje…'} value={text} onChange={e=>setText(e.target.value)} maxLength={1500}/><button type="button" className={'icon-button '+(voice.listening?'recording':'')} aria-label={voice.listening?'Detener dictado':'Dictar mensaje'} onClick={()=>voice.listening?voice.stop():voice.start()}><Icon name="mic" size={27}/></button></div><button className="send-button" aria-label="Enviar mensaje" disabled={busy||!text.trim()}><Icon name="send" size={27}/></button></form></div>
}
function Guided(){
 const {navigate,setCallOpen,command}=useBank();const [step,setStep]=useState(0);const [extra,setExtra]=useState(false)
 const steps=[['home','Toca Mis Productos','Está en la parte de abajo de la pantalla.'],['card','Selecciona tu crédito','Puede decir Crédito Personal, Crédito para Vehículo o similar.'],['file','Busca Próximo pago','Ahí verás la fecha y el monto de tu próximo pago.']]
 return <><Title subtitle="Tu próximo pago, más fácil." badge="Modo guiado"/><div className="page-content guided"><div className="guide-intro"><RoundIcon name="robot" size={48}/><div><h2>Te voy a guiar paso a paso.</h2><p>Aquí estamos para ayudarte.<br/>Puedes seguir estos pasos o hablarme por voz.</p></div></div><div className="question-heading"><h2>¿Cómo ver tu próximo pago?</h2><p>Sigue estos 3 pasos en la app:</p></div><div className="guide-steps">{steps.map(([icon,title,subtitle],i)=><button className={'guide-step '+(step===i?'current':'')} key={title} onClick={()=>{setStep(i);setExtra(false)}}><b>{i+1}</b><Icon name={icon} size={35}/><span><strong>{title}</strong><small>{subtitle}</small></span>{step>i&&<Icon name="check"/>}</button>)}</div>{extra&&<div className="info-box"><Icon name="info"/><p>{step===0?'Busca el icono de tarjeta en la barra inferior. Tócalo y luego elige la pestaña Créditos.':step===1?'Tu crédito aparece en una tarjeta blanca, con su nombre y número. El saldo pendiente está debajo.':'La fecha aparece junto a tu cuota mensual. También puedes tocar Necesito ayuda con este pago.'}</p></div>}<div className="stack-actions"><Button icon="check" onClick={()=>step<2?setStep(step+1):navigate('productos')}>{step<2?'Ya lo encontré':'Ver mi próximo pago'}</Button><Button secondary icon="search" onClick={()=>setExtra(true)}>No lo encuentro</Button><Button secondary icon="call" onClick={()=>{setCallOpen(true);command('callback')}}>Solicitar llamada</Button></div><button className="voice-guide" onClick={()=>setCallOpen(true)}><span className="mic-circle"><Icon name="mic" size={37}/></span><strong>Hablar con mi asistente</strong><span>Puedes responder por voz.</span></button><p className="security-note"><Icon name="lock" size={16}/>Nunca te pediremos contraseñas ni códigos de seguridad.</p></div></>
}
function Support(){const {state,command,navigate,setCallOpen}=useBank();return <><Title/><div className="page-content"><section className="preventive-card support-card"><div className="preventive-heading"><RoundIcon name="headset" alert size={42}/><div><h2>Tu caso necesita revisión personalizada</h2><p>Puedo ayudarte a solicitar apoyo de un asesor para continuar contigo.</p><p className="small">Un asesor podrá revisar tu caso y las alternativas disponibles.</p></div></div><div className="support-product card"><Icon name={productIcon(state.product.code)} size={38}/><div><h3>{state.product.name}</h3><p>Solicitud de revisión</p><span>N.° {state.product.number}</span></div><span className="badge">Requiere revisión</span></div><div className="stack-actions"><Button icon="call" disabled={!!state.support} onClick={()=>{setCallOpen(true);command('callback')}}>{state.support?'Solicitud registrada':'Solicitar llamada'}</Button><Button secondary onClick={()=>navigate('chat')}>Continuar por chat</Button></div><div className="support-note"><RoundIcon name="info" tone="blue"/><div><strong>No estás solo</strong><p>Estamos para ayudarte. Puedes continuar por chat mientras revisas tu solicitud.</p></div></div></section>{state.support&&<section className="receipt-card"><div className="receipt-heading"><RoundIcon name="check" tone="mint"/><div><h2>Solicitud registrada</h2><p>Tu solicitud quedó guardada.</p></div></div><dl><div><dt>Producto</dt><dd>{state.support.product}</dd></div><div><dt>N.° de solicitud</dt><dd>{state.support.id}</dd></div><div><dt>Estado</dt><dd><span className="badge">Pendiente</span></dd></div></dl><p className="simulation-note">Demostración: no se realizará una llamada bancaria real.</p></section>}</div></>}
function Messages(){
 const {state,navigate,command}=useBank();const [tab,setTab]=useState('Todos')
 return <><div className="simple-heading"><h1>Mensajería</h1><p>Aquí encontrarás mensajes importantes<br/>sobre tus productos y servicios.</p></div><div className="tabs">{['Todos','Notificaciones','Promociones'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="page-content">{tab==='Promociones'?<div className="empty-state"><RoundIcon name="gift" tone="pink"/><h2>Por ahora, sin promociones</h2><p>Este espacio está dedicado a ayudarte con tus productos.</p></div>:state.intervention.show?<section className="message-card"><div className="message-card-header"><RoundIcon name="whatsapp" tone="whatsapp"/><div><h3>Mensaje de Bancoagrícola</h3><span>Ahora</span></div><span className="badge">Recordatorio preventivo</span></div><div className="notification-bubble"><p>Hola, tienes un pago próximo.<br/>Puedes revisarlo desde Bancoagrícola aquí.</p><span>{timeLabel(state.created_at)}</span></div><div className="stack-actions"><Button onClick={()=>navigate('ayuda')}>Abrir en la app</Button><Button secondary onClick={()=>command('snooze')}>Más tarde</Button></div><div className="message-footer"><RoundIcon name="calendar" alert/><div><strong>Puedes continuar en BA A Tiempo</strong><p>Revisar tus pagos con anticipación te ayuda a mantener tus finanzas al día.</p></div></div></section>:<div className="quiet-card"><RoundIcon name="check" tone="mint"/><div><h2>Todo tranquilo por aquí</h2><p>No tienes recordatorios preventivos pendientes.</p></div></div>}<button className="option-row" onClick={()=>navigate('whatsapp')}><RoundIcon name="whatsapp" tone="mint"/><span><strong>Continuar por WhatsApp</strong><small>La misma conversación, en otro canal.</small></span><Icon name="arrow"/></button><button className="option-row" onClick={()=>navigate('chat')}><RoundIcon name="chat" tone="blue"/><span><strong>Ver todos los mensajes</strong><small>Tu conversación con BA A Tiempo.</small></span><Icon name="arrow"/></button><a className="external-whatsapp" href="https://wa.me/?text=Hola%2C%20quiero%20conocer%20BA%20A%20Tiempo%20%28demostraci%C3%B3n%29" target="_blank" rel="noreferrer">Abrir WhatsApp externo <Icon name="arrow" size={15}/></a><p className="simulation-note">La demo integrada no envía mensajes externos. El enlace abre WhatsApp para que tú elijas un destinatario.</p></div></>
}
function Receipt(){
 const {state,navigate,command}=useBank();const receipt=state.receipt
 if(!receipt)return <><Title title="Comprobantes"/><div className="empty-state"><RoundIcon name="file"/><h2>Aún no hay comprobantes</h2><Button onClick={()=>navigate('productos')}>Ver mi producto</Button></div></>
 const download=()=>{const text=['BA A Tiempo · Comprobante de operación simulada',receipt.id,receipt.product,receipt.title,receipt.amount!=null?money(receipt.amount):dateLabel(receipt.date),receipt.at,'Datos ficticios. Sin operaciones bancarias reales.'].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${receipt.id}.txt`;a.click();URL.revokeObjectURL(url)}
 return <><Title title="Tu comprobante" back="productos"/><div className="page-content"><div className="receipt-intro"><RoundIcon name="check" tone="mint" size={42}/><h1>Listo, quedó registrado</h1><p>Tu producto se actualizó en este momento.</p></div><section className="receipt-card"><h2>{receipt.title}</h2><dl><div><dt>Producto</dt><dd>{receipt.product}</dd></div>{receipt.amount!=null&&<div><dt>Monto pagado</dt><dd>{money(receipt.amount)}</dd></div>}{receipt.date&&<div><dt>Nueva fecha</dt><dd>{dateLabel(receipt.date)}</dd></div>}{receipt.percentage&&<div><dt>Porcentaje de ingresos</dt><dd>{Number((receipt.percentage*100).toFixed(2))}%</dd></div>}<div><dt>N.° de comprobante</dt><dd>{receipt.id}</dd></div><div><dt>Estado</dt><dd><span className="badge mint">Registrado</span></dd></div></dl><p className="simulation-note">Operación simulada. No se han movido fondos reales.</p></section><ProductCard/><div className="stack-actions standalone"><Button icon="check" onClick={async()=>{await command('seen');navigate('productos')}}>Ya veo el cambio</Button><Button secondary icon="file" onClick={download}>Guardar comprobante</Button></div></div></>
}
function History(){const {state,navigate}=useBank();const events=state.events.filter(e=>e.type!=='BARRIER_CLASSIFIED').slice().reverse();return <><Title title="Mi historial" back="productos"/><div className="page-content"><p className="muted">Tus gestiones y operaciones en esta demostración.</p>{!events.length?<div className="empty-state"><RoundIcon name="file" tone="blue"/><h2>Tu historia comienza aquí</h2><p>Aquí aparecerán tus pagos, acuerdos y solicitudes.</p><Button onClick={()=>navigate('productos')}>Ver mi producto</Button></div>:events.map((e,i)=><div className="history-event card" key={e.id||i}><RoundIcon name={e.type==='CALLBACK_REQUESTED'?'headset':'check'} tone="mint"/><div><h3>{e.title||'Solicitud de atención registrada'}</h3><p>{e.id||e.channel||''}</p><span>{new Date(e.at).toLocaleString('es-SV')}</span></div>{e.amount!=null&&<strong>{money(e.amount)}</strong>}</div>)}</div></>}
function Profile(){const {state,command,create,setCallOpen}=useBank();const [scenarios,setScenarios]=useState([]);useEffect(()=>{fetch('/api/scenarios').then(r=>r.json()).then(setScenarios).catch(()=>{})},[]);return <><Title title="Mi perfil"/><div className="page-content"><div className="profile-card card"><RoundIcon name="user" tone="purple" size={40}/><h2>{state.name}</h2><p>Cliente de demostración</p><span className="badge">Datos ficticios</span></div><section className="card preferences"><h2>¿Cómo prefieres conversar?</h2><p>Tú eliges el canal que te resulte más cómodo.</p><div className="channel-options">{[['APP_PUSH','chat','En la app'],['WHATSAPP','whatsapp','WhatsApp'],['CALL','call','Llamada']].map(([id,icon,title])=><button aria-pressed={state.channel===id} className={state.channel===id?'selected':''} key={id} onClick={()=>command('channel',{channel:id})}><Icon name={icon}/>{title}</button>)}</div><Button secondary icon="call" onClick={()=>setCallOpen(true)}>Conversar ahora</Button></section><section className="card demo-settings"><h2>Explorar la demostración</h2><p>Elige otro caso para iniciar una sesión independiente. Tu sesión anterior conserva sus operaciones.</p><label htmlFor="scenario">Situación del cliente</label><select id="scenario" value={state.customer_id} onChange={e=>create(e.target.value)}>{scenarios.map(s=><option key={s.id} value={s.customer_id}>{s.label}</option>)}</select><Button secondary onClick={()=>create(state.customer_id)}>Reiniciar este caso</Button></section></div></>}
function Services(){
 const {page,navigate,state,command}=useBank();const [notice,setNotice]=useState(false)
 const calendar=async()=>{const result=await command('reminder');if(!result)return;const day=state.product.due_date.replaceAll('-','');const ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//BA A Tiempo//Demo//ES\r\nBEGIN:VEVENT\r\nUID:${state.id}@ba-demo\r\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}\r\nDTSTART;VALUE=DATE:${day}\r\nSUMMARY:Revisar próximo pago - BA A Tiempo\r\nDESCRIPTION:Recordatorio personal de demostración.\r\nEND:VEVENT\r\nEND:VCALENDAR`;const url=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download='mi-proximo-pago.ics';a.click();URL.revokeObjectURL(url);setNotice(true)}
 const titles={gestiones:'Gestiones',parati:'Para Ti',transferir:'Transferir dinero',servicios:'Pagos y recargas',qr:'Mi QR'}
 return <><Title title={titles[page]||'BA A Tiempo'}/><div className="page-content">{page==='parati'?<><div className="guide-intro"><RoundIcon name="gift" tone="pink"/><div><h2>Pequeños hábitos, más tranquilidad</h2><p>Organizar tu próximo pago es una forma de cuidar lo que estás construyendo.</p></div></div><section className="card editorial"><h2>Haz espacio para tus metas</h2><p>Revisa la fecha de tu ingreso y tus gastos esenciales. Si este mes se complica, habla con nosotros antes de tu próximo pago.</p><Button onClick={()=>navigate('ayuda')}>Revisar mis opciones</Button></section></>:['transferir','servicios','qr'].includes(page)?<div className="empty-state"><RoundIcon name={page==='qr'?'qr':'transfer'} tone="blue"/><h2>{page==='qr'?'Tu seguridad va primero':'Este espacio es una demostración'}</h2><p>{page==='qr'?'No generamos códigos bancarios reales. Puedes explorar tu próximo pago y la asistencia de BA A Tiempo.':'Las transferencias, recargas y pagos de servicios no mueven fondos reales. Prueba el pago simulado de tu crédito en Mis Productos.'}</p><Button onClick={()=>navigate('productos')}>Ir a Mis Productos</Button></div>:<><button className="option-row" onClick={()=>navigate('ayuda')}><RoundIcon name="calendar"/><span><strong>Ayuda con mi próximo pago</strong><small>Encuentra una alternativa para ti.</small></span><Icon name="arrow"/></button><button className="option-row" onClick={()=>navigate('guided')}><RoundIcon name="phone" tone="blue"/><span><strong>Aprender a usar la app</strong><small>Te guiamos paso a paso.</small></span><Icon name="arrow"/></button><button className="option-row" onClick={()=>navigate('support')}><RoundIcon name="headset" tone="purple"/><span><strong>Solicitar atención</strong><small>Una persona puede ayudarte.</small></span><Icon name="arrow"/></button></>}<section className="card calendar-card"><RoundIcon name="calendar"/><div><h3>Tu próximo pago, presente</h3><p>{dateLabel(state.product.due_date)}</p></div><Button secondary onClick={calendar}>{notice||state.reminder?'Descargar de nuevo':'Guardar en calendario'}</Button></section>{notice&&<p className="saved-note" role="status">Recordatorio descargado. Ábrelo para añadirlo a tu calendario.</p>}</div></>
}
function Confirmation(){const {state,command,busy,error}=useBank();const offer=state.pending_offer;const dialog=useRef(null);useEffect(()=>{if(offer&&!dialog.current?.open)dialog.current?.showModal();if(!offer&&dialog.current?.open)dialog.current.close()},[offer]);if(!offer)return null;const amount=offer.min_amount||offer.amount||(offer.type==='PAY_NOW'?state.product.remaining:null);return <dialog ref={dialog} className="confirmation-dialog" aria-labelledby="confirm-title" onCancel={e=>{e.preventDefault();command('cancel')}}><button className="icon-button modal-close" aria-label="Cancelar operación" onClick={()=>command('cancel')}><Icon name="close"/></button><RoundIcon name={offer.icon||'card'}/><h2 id="confirm-title">Revisa antes de confirmar</h2><p>{offer.title}</p><div className="confirmation-summary"><strong>{state.product.name}</strong>{amount!=null&&<div><span>Monto</span><b>{money(amount)}</b></div>}{offer.date&&<div><span>Fecha autorizada</span><b>{dateLabel(offer.date)}</b></div>}{offer.percentage&&<div><span>Porcentaje de ingresos</span><b>{Number((offer.percentage*100).toFixed(2))}%</b></div>}{amount!=null&&<div><span>Cuenta de origen</span><b>Ahorro {state.accounts[0].number}</b></div>}<div><span>Saldo disponible</span><b>{money(state.accounts[0].balance)}</b></div></div><p className="simulation-note">Estás confirmando una operación simulada. No se moverá dinero real.</p>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="stack-actions"><Button icon="check" disabled={busy} onClick={()=>command('confirm',{token:offer.token})}>Confirmar {amount!=null?'pago':'opción'}</Button><Button secondary onClick={()=>command('cancel')}>Volver sin confirmar</Button></div></dialog>}
function BankingApp(){const {state,error,setError,busy,page,navigate,create,callOpen}=useBank();useEffect(()=>{document.title='BA A Tiempo · Bancoagrícola'},[]);if(!state)return <div className="loading-page"><div className="brand"><span/><span/><span/></div><h1>BA A Tiempo</h1><p>{error||'Preparando tu espacio…'}</p>{error?<button className="button primary" onClick={()=>create()}>Volver a intentar</button>:<div className="loader"/>}</div>;const pages={inicio:<Home/>,productos:<Products key="creditos"/>,cuentas:<Products key="cuentas" initialTab="cuentas"/>,ayuda:<Help/>,chat:<Chat/>,whatsapp:<Chat whatsapp/>,guided:<Guided/>,support:<Support/>,mensajeria:<Messages/>,receipt:<Receipt/>,historial:<History/>,perfil:<Profile/>};return <div className={'app-shell '+(callOpen?'with-call':'')}><Header/><main id="main-content">{pages[page]||<Services/>}</main><div className="demo-disclaimer"><Icon name="lock" size={12}/><span>Prototipo · Datos ficticios · Sin operaciones reales</span><button onClick={()=>navigate('perfil')}>Cambiar caso</button></div><BottomNav/>{busy&&<div className="progress-line" role="progressbar" aria-label="Procesando"/>}{error&&!state.pending_offer&&<div className="error-toast" role="alert"><Icon name="info"/><span>{error}</span><button className="icon-button" aria-label="Cerrar aviso" onClick={()=>setError(null)}><Icon name="close" size={18}/></button></div>}<Confirmation/><VoiceCall/></div>}
export default function App(){return <BankingProvider><BankingApp/></BankingProvider>}
